[tidal]
enabled = true
quality = LOSSLESS
client_id =
client_secret =
widevine_cdm_path =
fetch_album_covers = false
playlist_cache_refresh_secs = 300
pagination_max_results = 40
login_web_port = 8989
http_timeout = 3.05, 1.5
